SOURCES += \
	src/crypto/crypto.cc
	# src/crypto/3rdparty/cryptopp/dh.cc \
	# src/crypto/3rdparty/cryptopp/integer.cc \
	# src/crypto/3rdparty/cryptopp/3way.cc \
	# src/crypto/3rdparty/cryptopp/adhoc.cc \
	# src/crypto/3rdparty/cryptopp/adler32.cc \
	# src/crypto/3rdparty/cryptopp/algebra.cc \
	# src/crypto/3rdparty/cryptopp/algparam.cc \
	# src/crypto/3rdparty/cryptopp/allocate.cc \
	# src/crypto/3rdparty/cryptopp/arc4.cc \
	# src/crypto/3rdparty/cryptopp/aria.cc \
	# src/crypto/3rdparty/cryptopp/aria_simd.cc \
	# src/crypto/3rdparty/cryptopp/ariatab.cc \
	# src/crypto/3rdparty/cryptopp/asn.cc \
	# src/crypto/3rdparty/cryptopp/authenc.cc \
	# src/crypto/3rdparty/cryptopp/base32.cc \
	# src/crypto/3rdparty/cryptopp/base64.cc \
	# src/crypto/3rdparty/cryptopp/basecode.cc \
	# src/crypto/3rdparty/cryptopp/bench1.cc \
	# src/crypto/3rdparty/cryptopp/bench2.cc \
	# src/crypto/3rdparty/cryptopp/bench3.cc \
	# src/crypto/3rdparty/cryptopp/bfinit.cc \
	# src/crypto/3rdparty/cryptopp/blake2b_simd.cc \
	# src/crypto/3rdparty/cryptopp/blake2.cc \
	# src/crypto/3rdparty/cryptopp/blake2s_simd.cc \
	# src/crypto/3rdparty/cryptopp/blowfish.cc \
	# src/crypto/3rdparty/cryptopp/blumshub.cc \
	# src/crypto/3rdparty/cryptopp/camellia.cc \
	# src/crypto/3rdparty/cryptopp/cast.cc \
	# src/crypto/3rdparty/cryptopp/casts.cc \
	# src/crypto/3rdparty/cryptopp/cbcmac.cc \
	# src/crypto/3rdparty/cryptopp/ccm.cc \
	# src/crypto/3rdparty/cryptopp/chacha_avx.cc \
	# src/crypto/3rdparty/cryptopp/chacha.cc \
	# src/crypto/3rdparty/cryptopp/chachapoly.cc \
	# src/crypto/3rdparty/cryptopp/chacha_simd.cc \
	# src/crypto/3rdparty/cryptopp/cham.cc \
	# src/crypto/3rdparty/cryptopp/cham_simd.cc \
	# src/crypto/3rdparty/cryptopp/channels.cc \
	# src/crypto/3rdparty/cryptopp/cmac.cc \
	# src/crypto/3rdparty/cryptopp/cpu.cc \
	# src/crypto/3rdparty/cryptopp/crc.cc \
	# src/crypto/3rdparty/cryptopp/crc_simd.cc \
	# src/crypto/3rdparty/cryptopp/cryptlib.cc \
	# src/crypto/3rdparty/cryptopp/darn.cc \
	# src/crypto/3rdparty/cryptopp/datatest.cc \
	# src/crypto/3rdparty/cryptopp/default.cc \
	# src/crypto/3rdparty/cryptopp/des.cc \
	# src/crypto/3rdparty/cryptopp/dessp.cc \
	# src/crypto/3rdparty/cryptopp/dh2.cc \
	# src/crypto/3rdparty/cryptopp/dll.cc \
	# src/crypto/3rdparty/cryptopp/dlltest.cc \
	# src/crypto/3rdparty/cryptopp/donna_32.cc \
	# src/crypto/3rdparty/cryptopp/donna_64.cc \
	# src/crypto/3rdparty/cryptopp/donna_sse.cc \
	# src/crypto/3rdparty/cryptopp/dsa.cc \
	# src/crypto/3rdparty/cryptopp/eax.cc \
	# src/crypto/3rdparty/cryptopp/ec2n.cc \
	# src/crypto/3rdparty/cryptopp/eccrypto.cc \
	# src/crypto/3rdparty/cryptopp/ecp.cc \
	# src/crypto/3rdparty/cryptopp/elgamal.cc \
	# src/crypto/3rdparty/cryptopp/emsa2.cc \
	# src/crypto/3rdparty/cryptopp/eprecomp.cc \
	# src/crypto/3rdparty/cryptopp/esign.cc \
	# src/crypto/3rdparty/cryptopp/files.cc \
	# src/crypto/3rdparty/cryptopp/filters.cc \
	# src/crypto/3rdparty/cryptopp/fips140.cc \
	# src/crypto/3rdparty/cryptopp/fipsalgt.cc \
	# src/crypto/3rdparty/cryptopp/fipstest.cc \
	# src/crypto/3rdparty/cryptopp/gcm.cc \
	# src/crypto/3rdparty/cryptopp/gcm_simd.cc \
	# src/crypto/3rdparty/cryptopp/gf2_32.cc \
	# src/crypto/3rdparty/cryptopp/gf256.cc \
	# src/crypto/3rdparty/cryptopp/gf2n.cc \
	# src/crypto/3rdparty/cryptopp/gf2n_simd.cc \
	# src/crypto/3rdparty/cryptopp/gfpcrypt.cc \
	# src/crypto/3rdparty/cryptopp/gost.cc \
	# src/crypto/3rdparty/cryptopp/gzip.cc \
	# src/crypto/3rdparty/cryptopp/hc128.cc \
	# src/crypto/3rdparty/cryptopp/hc256.cc \
	# src/crypto/3rdparty/cryptopp/hex.cc \
	# src/crypto/3rdparty/cryptopp/hight.cc \
	# src/crypto/3rdparty/cryptopp/hmac.cc \
	# src/crypto/3rdparty/cryptopp/hrtimer.cc \
	# src/crypto/3rdparty/cryptopp/ida.cc \
	# src/crypto/3rdparty/cryptopp/idea.cc \
	# src/crypto/3rdparty/cryptopp/integer.cc \
	# src/crypto/3rdparty/cryptopp/iterhash.cc \
	# src/crypto/3rdparty/cryptopp/kalyna.cc \
	# src/crypto/3rdparty/cryptopp/kalynatab.cc \
	# src/crypto/3rdparty/cryptopp/keccak_core.cc \
	# src/crypto/3rdparty/cryptopp/keccak.cc \
	# src/crypto/3rdparty/cryptopp/keccak_simd.cc \
	# src/crypto/3rdparty/cryptopp/lea.cc \
	# src/crypto/3rdparty/cryptopp/lea_simd.cc \
	# src/crypto/3rdparty/cryptopp/luc.cc \
	# src/crypto/3rdparty/cryptopp/mars.cc \
	# src/crypto/3rdparty/cryptopp/marss.cc \
	# src/crypto/3rdparty/cryptopp/md2.cc \
	# src/crypto/3rdparty/cryptopp/md4.cc \
	# src/crypto/3rdparty/cryptopp/md5.cc \
	# src/crypto/3rdparty/cryptopp/misc.cc \
	# src/crypto/3rdparty/cryptopp/modes.cc \
	# src/crypto/3rdparty/cryptopp/mqueue.cc \
	# src/crypto/3rdparty/cryptopp/mqv.cc \
	# src/crypto/3rdparty/cryptopp/nbtheory.cc \
	# src/crypto/3rdparty/cryptopp/neon_simd.cc \
	# src/crypto/3rdparty/cryptopp/oaep.cc \
	# src/crypto/3rdparty/cryptopp/osrng.cc \
	# src/crypto/3rdparty/cryptopp/padlkrng.cc \
	# src/crypto/3rdparty/cryptopp/panama.cc \
	# src/crypto/3rdparty/cryptopp/pch.cc \
	# src/crypto/3rdparty/cryptopp/pkcspad.cc \
	# src/crypto/3rdparty/cryptopp/poly1305.cc \
	# src/crypto/3rdparty/cryptopp/polynomi.cc \
	# src/crypto/3rdparty/cryptopp/ppc_power7.cc \
	# src/crypto/3rdparty/cryptopp/ppc_power8.cc \
	# src/crypto/3rdparty/cryptopp/ppc_power9.cc \
	# src/crypto/3rdparty/cryptopp/ppc_simd.cc \
	# src/crypto/3rdparty/cryptopp/pssr.cc \
	# src/crypto/3rdparty/cryptopp/pubkey.cc \
	# src/crypto/3rdparty/cryptopp/queue.cc \
	# src/crypto/3rdparty/cryptopp/rabbit.cc \
	# src/crypto/3rdparty/cryptopp/rabin.cc \
	# src/crypto/3rdparty/cryptopp/randpool.cc \
	# src/crypto/3rdparty/cryptopp/rc2.cc \
	# src/crypto/3rdparty/cryptopp/rc5.cc \
	# src/crypto/3rdparty/cryptopp/rc6.cc \
	# src/crypto/3rdparty/cryptopp/rdrand.cc \
	# src/crypto/3rdparty/cryptopp/rdtables.cc \
	# src/crypto/3rdparty/cryptopp/regtest1.cc \
	# src/crypto/3rdparty/cryptopp/regtest2.cc \
	# src/crypto/3rdparty/cryptopp/regtest3.cc \
	# src/crypto/3rdparty/cryptopp/regtest4.cc \
	# src/crypto/3rdparty/cryptopp/rijndael.cc \
	# src/crypto/3rdparty/cryptopp/rijndael_simd.cc \
	# src/crypto/3rdparty/cryptopp/ripemd.cc \
	# src/crypto/3rdparty/cryptopp/rng.cc \
	# src/crypto/3rdparty/cryptopp/rsa.cc \
	# src/crypto/3rdparty/cryptopp/rw.cc \
	# src/crypto/3rdparty/cryptopp/safer.cc \
	# src/crypto/3rdparty/cryptopp/salsa.cc \
	# src/crypto/3rdparty/cryptopp/scrypt.cc \
	# src/crypto/3rdparty/cryptopp/seal.cc \
	# src/crypto/3rdparty/cryptopp/seed.cc \
	# src/crypto/3rdparty/cryptopp/serpent.cc \
	# src/crypto/3rdparty/cryptopp/sha3.cc \
	# src/crypto/3rdparty/cryptopp/shacal2.cc \
	# src/crypto/3rdparty/cryptopp/shacal2_simd.cc \
	# src/crypto/3rdparty/cryptopp/sha.cc \
	# src/crypto/3rdparty/cryptopp/shake.cc \
	# src/crypto/3rdparty/cryptopp/sharkbox.cc \
	# src/crypto/3rdparty/cryptopp/shark.cc \
	# src/crypto/3rdparty/cryptopp/sha_simd.cc \
	# src/crypto/3rdparty/cryptopp/simeck.cc \
	# src/crypto/3rdparty/cryptopp/simeck_simd.cc \
	# src/crypto/3rdparty/cryptopp/simon128_simd.cc \
	# src/crypto/3rdparty/cryptopp/simon64_simd.cc \
	# src/crypto/3rdparty/cryptopp/simon.cc \
	# src/crypto/3rdparty/cryptopp/simple.cc \
	# src/crypto/3rdparty/cryptopp/skipjack.cc \
	# src/crypto/3rdparty/cryptopp/sm3.cc \
	# src/crypto/3rdparty/cryptopp/sm4.cc \
	# src/crypto/3rdparty/cryptopp/sm4_simd.cc \
	# src/crypto/3rdparty/cryptopp/sosemanuk.cc \
	# src/crypto/3rdparty/cryptopp/speck128_simd.cc \
	# src/crypto/3rdparty/cryptopp/speck64_simd.cc \
	# src/crypto/3rdparty/cryptopp/speck.cc \
	# src/crypto/3rdparty/cryptopp/square.cc \
	# src/crypto/3rdparty/cryptopp/squaretb.cc \
	# src/crypto/3rdparty/cryptopp/sse_simd.cc \
	# src/crypto/3rdparty/cryptopp/strciphr.cc \
	# src/crypto/3rdparty/cryptopp/tea.cc \
	# src/crypto/3rdparty/cryptopp/test.cc \
	# src/crypto/3rdparty/cryptopp/tftables.cc \
	# src/crypto/3rdparty/cryptopp/threefish.cc \
	# src/crypto/3rdparty/cryptopp/tiger.cc \
	# src/crypto/3rdparty/cryptopp/tigertab.cc \
	# src/crypto/3rdparty/cryptopp/ttmac.cc \
	# src/crypto/3rdparty/cryptopp/tweetnacl.cc \
	# src/crypto/3rdparty/cryptopp/twofish.cc \
	# src/crypto/3rdparty/cryptopp/validat0.cc \
	# src/crypto/3rdparty/cryptopp/validat10.cc \
	# src/crypto/3rdparty/cryptopp/validat1.cc \
	# src/crypto/3rdparty/cryptopp/validat2.cc \
	# src/crypto/3rdparty/cryptopp/validat3.cc \
	# src/crypto/3rdparty/cryptopp/validat4.cc \
	# src/crypto/3rdparty/cryptopp/validat5.cc \
	# src/crypto/3rdparty/cryptopp/validat6.cc \
	# src/crypto/3rdparty/cryptopp/validat7.cc \
	# src/crypto/3rdparty/cryptopp/validat8.cc \
	# src/crypto/3rdparty/cryptopp/validat9.cc \
	# src/crypto/3rdparty/cryptopp/vmac.cc \
	# src/crypto/3rdparty/cryptopp/wake.cc \
	# src/crypto/3rdparty/cryptopp/whrlpool.cc \
	# src/crypto/3rdparty/cryptopp/xed25519.cc \
	# src/crypto/3rdparty/cryptopp/xtr.cc \
	# src/crypto/3rdparty/cryptopp/xtrcrypt.cc \
	# src/crypto/3rdparty/cryptopp/xts.cc \
	# src/crypto/3rdparty/cryptopp/zdeflate.cc \
	# src/crypto/3rdparty/cryptopp/zinflate.cc \
	# src/crypto/3rdparty/cryptopp/zlib.cpp.cc
